services:
  comic_shelf:
    container_name: shelf-backend
    image: ghcr.io/natashalysakova/comic-shelf:latest
    ports:
      - 5297:8080
    networks:
      - shelf-network
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    env_file:
      - .env

  db:
    container_name: shelf-db
    image: mariadb:latest
    ports:
      - 3308:3306
    networks:
      - shelf-network
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env

networks:
  shelf-network:
    driver: bridge

volumes:
  dbdata:
    driver: local